name: dart_untis_mobile
description: "A pure dart library implementing the Untis Mobile API (https://www.untis.at/produkte/webuntis/untis-mobile-app)."
repository: https://github.com/Code42Maestro/dart_untis_mobile
version: 1.0.1
topics:
  - untis
  - webuntis
  - api
  - web

  # This package supports all platforms.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  base32: ^2.1.3
  crypto: ^3.0.3
  equatable: ^2.0.5
  http: ^1.1.0

dev_dependencies:
  all_lint_rules_community: ^0.0.38
  test: ^1.24.2
