name: Publish to pub.dev

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        uses: nikosportolos/dart_package@v0.2.0
        with:
          publish: true
          pubdev_token: ${{ secrets.CREDENTIAL_BASE64 }}
          sdk: "flutter"
          line_length: 80