name: Publish to pub.dev

on:
  release:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.10
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Format code
        run: dart format --fix .
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
      - name: Publish
        uses: nikosportolos/dart_package@v0.2.0
        with:
          credential: ${{ secrets.CREDENTIAL_BASE64 }}
          flutter_package: false
          skip_test: true
