name: Publish to pub.dev

on:
  workflow_dispatch:
  push:
    paths: [ "pubspec.yaml" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: "mkdir test"
      - name: Publish
        uses: nikosportolos/dart_package@v0.2.0
        with:
          publish: true
          skip_tests: true
          analyze_directories: "lib"
          pubdev_token: ${{ secrets.CREDENTIAL_BASE64 }}
          sdk: "flutter"
          line_length: 80